# Generated by Django 2.2.4 on 2026-06-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0007_claimedreward_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
