# Generated by Django 2.2.4 on 2026-06-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0008_reward_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='proof',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='families_app.TaskSubmission')),
            ],
        ),
    ]
