# Generated by Django 2.2.4 on 2026-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0009_auto_20260609_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
