# Generated by Django 2.2.4 on 2026-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0010_tasksubmission_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suggested_time',
            field=models.CharField(blank=True, choices=[('', 'غير محدد'), ('الصبح', 'الصبح'), ('الظهر', 'الظهر'), ('العصر', 'العصر'), ('بعد المغرب', 'بعد المغرب')], default='', max_length=20),
        ),
    ]
