# Generated by Django 2.2.4 on 2026-06-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0011_task_suggested_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='approval_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
