# Generated by Django 2.2.4 on 2026-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0012_tasksubmission_approval_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='child_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
