# Generated by Django 2.2.4 on 2026-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0013_tasksubmission_child_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
